export const AtlantaHawks = [{
  "id": "AtlantaHawks_1",
  "firstName": "Kent",
  "lastName": "Bazemore",
  "position": "SF",
  "salary": 16910113,
  "contractYears": 3,
  "tradeEligible": true
}, {
  "id": "AtlantaHawks_2",
  "firstName": "Dennis",
  "lastName": "Schroder",
  "position": "PG",
  "salary": 15500000,
  "contractYears": 4,
  "tradeEligible": true
}, {
  "id": "AtlantaHawks_3",
  "firstName": "Mason",
  "lastName": "Plumlee",
  "position": "SF",
  "salary": 12500000,
  "contractYears": 3,
  "tradeEligible": true
}, {
  "id": "AtlantaHawks_4",
  "firstName": "Marco",
  "lastName": "Belinelli",
  "position": "SF",
  "salary": 6060606,
  "contractYears": 1,
  "tradeEligible": true
}, {
  "id": "AtlantaHawks_5",
  "firstName": "Ersan",
  "lastName": "Ilyasova",
  "position": "PF",
  "salary": 6000000,
  "contractYears": 1,
  "tradeEligible": false
}, {
  "id": "AtlantaHawks_6",
  "firstName": "Dewayne",
  "lastName": "Dedmon",
  "position": "C",
  "salary": 6000000,
  "contractYears": 2,
  "tradeEligible": false
}, {
  "id": "AtlantaHawks_7",
  "firstName": "Mike",
  "lastName": "Muscala",
  "position": "PF",
  "salary": 5000000,
  "contractYears": 2,
  "tradeEligible": false
}, {
  "id": "AtlantaHawks_8",
  "firstName": "Malcolm",
  "lastName": "Delaney",
  "position": "G",
  "salary": 2500000,
  "contractYears": 1,
  "tradeEligible": true
}, {
  "id": "AtlantaHawks_9",
  "firstName": "Taruean",
  "lastName": "Prince",
  "position": "SF",
  "salary": 2422560,
  "contractYears": 3,
  "tradeEligible": true
}, {
  "id": "AtlantaHawks_10",
  "firstName": "John",
  "lastName": "Collins",
  "position": "PF",
  "salary": 1936920,
  "contractYears": 4,
  "tradeEligible": true
}, {
  "id": "AtlantaHawks_11",
  "firstName": "DeAndre'",
  "lastName": "Bembry",
  "position": "SF",
  "salary": 1567200,
  "contractYears": 3,
  "tradeEligible": true
}, {
  "id": "AtlantaHawks_12",
  "firstName": "Nicolas",
  "lastName": "Brussino",
  "position": "SF",
  "salary": 1312611,
  "contractYears": 2,
  "tradeEligible": false
}, {
  "id": "AtlantaHawks_13",
  "firstName": "Tyler",
  "lastName": "Dorsey",
  "position": "SG",
  "salary": 815615,
  "contractYears": 2,
  "tradeEligible": false
}];

export const BostonCeltics = [{
  "id": "BostonCeltics_1",
  "firstName": "Gordon",
  "lastName": "Hayward",
  "position": "SF",
  "salary": 29727900,
  "contractYears": 4,
  "tradeEligible": false
}, {
  "id": "BostonCeltics_2",
  "firstName": "Al",
  "lastName": "Horford",
  "position": "C",
  "salary": 27734406,
  "contractYears": 3,
  "tradeEligible": true
}, {
  "id": "BostonCeltics_3",
  "firstName": "Jae",
  "lastName": "Crowder",
  "position": "SF",
  "salary": 6796117,
  "contractYears": 3,
  "tradeEligible": true
}, {
  "id": "BostonCeltics_4",
  "firstName": "Isaiah",
  "lastName": "Thomas",
  "position": "PG",
  "salary": 6261395,
  "contractYears": 1,
  "tradeEligible": true
}, {
  "id": "BostonCeltics_5",
  "firstName": "Alan",
  "lastName": "Williams",
  "position": "C",
  "salary": 6000000,
  "contractYears": 3,
  "tradeEligible": false
}, {
  "id": "BostonCeltics_6",
  "firstName": "Jayson",
  "lastName": "Tatum",
  "position": "SF",
  "salary": 5645400,
  "contractYears": 4,
  "tradeEligible": true
}, {
  "id": "BostonCeltics_7",
  "firstName": "Marcus",
  "lastName": "Morris",
  "position": "PF",
  "salary": 5000000,
  "contractYears": 2,
  "tradeEligible": true
}, {
  "id": "BostonCeltics_8",
  "firstName": "Jaylen",
  "lastName": "Brown",
  "position": "SF",
  "salary": 4956480,
  "contractYears": 3,
  "tradeEligible": true
}, {
  "id": "BostonCeltics_9",
  "firstName": "Marcus",
  "lastName": "Smart",
  "position": "PG",
  "salary": 4538020,
  "contractYears": 2,
  "tradeEligible": true
}, {
  "id": "BostonCeltics_10",
  "firstName": "Aron",
  "lastName": "Baynes",
  "position": "C",
  "salary": 4238000,
  "contractYears": 1,
  "tradeEligible": false
}, {
  "id": "BostonCeltics_11",
  "firstName": "Guerschon",
  "lastName": "Yabusele",
  "position": "SG",
  "salary": 2247480,
  "contractYears": 4,
  "tradeEligible": false
}, {
  "id": "BostonCeltics_12",
  "firstName": "Terry",
  "lastName": "Rozier",
  "position": "PG",
  "salary": 1988520,
  "contractYears": 2,
  "tradeEligible": true
}, {
  "id": "BostonCeltics_14",
  "firstName": "Ante",
  "lastName": "Zizic",
  "position": "PF",
  "salary": 1645200,
  "contractYears": 4,
  "tradeEligible": true
}, {
  "id": "BostonCeltics_15",
  "firstName": "Shane",
  "lastName": "Larkin",
  "position": "PG",
  "salary": 1471382,
  "contractYears": 1,
  "tradeEligible": false
}, {
  "id": "BostonCeltics_16",
  "firstName": "Semi",
  "lastName": "Ojeleye",
  "position": "PF",
  "salary": 1291892,
  "contractYears": 4,
  "tradeEligible": false
}, {
  "id": "BostonCeltics_17",
  "firstName": "Abdel",
  "lastName": "Nader",
  "position": "SF",
  "salary": 1167333,
  "contractYears": 4,
  "tradeEligible": false
}, {
  "id": "BostonCeltics_18",
  "firstName": "Daniel",
  "lastName": "Theis",
  "position": "PF",
  "salary": 815615,
  "contractYears": 2,
  "tradeEligible": false
}];

export const BrooklynNets = [{
  "id": "BrooklynNets_1",
  "firstName": "Allen",
  "lastName": "Crabbe",
  "position": "SG",
  "salary": 19332500,
  "contractYears": 3,
  "tradeEligible": true
}, {
  "id": "BrooklynNets_2",
  "firstName": "Timofey",
  "lastName": "Mozgov",
  "position": "C",
  "salary": 15280000,
  "contractYears": 3,
  "tradeEligible": true
}, {
  "id": "BrooklynNets_3",
  "firstName": "Demarre",
  "lastName": "Carroll",
  "position": "SF",
  "salary": 14800000,
  "contractYears": 2,
  "tradeEligible": true
}, {
  "id": "BrooklynNets_4",
  "firstName": "Jeremy",
  "lastName": "Lin",
  "position": "PG",
  "salary": 12000000,
  "contractYears": 2,
  "tradeEligible": true
}, {
  "id": "BrooklynNets_5",
  "firstName": "Trevor",
  "lastName": "Booker",
  "position": "PF",
  "salary": 9125000,
  "contractYears": 1,
  "tradeEligible": true
}, {
  "id": "BrooklynNets_6",
  "firstName": "D'Angelo",
  "lastName": "Russell",
  "position": "PG",
  "salary": 5562360,
  "contractYears": 2,
  "tradeEligible": true
}, {
  "id": "BrooklynNets_7",
  "firstName": "Jarrett",
  "lastName": "Allen",
  "position": "C",
  "salary": 1713720,
  "contractYears": 4,
  "tradeEligible": false
}, {
  "id": "BrooklynNets_8",
  "firstName": "Quincy",
  "lastName": "Ancy",
  "position": "SF",
  "salary": 1709538,
  "contractYears": 1,
  "tradeEligible": true
}, {
  "id": "BrooklynNets_9",
  "firstName": "Caris",
  "lastName": "LeVert",
  "position": "SG",
  "salary": 1632480,
  "contractYears": 3,
  "tradeEligible": true
}, {
  "id": "BrooklynNets_10",
  "firstName": "Sean",
  "lastName": "Kilpatrick",
  "position": "SG",
  "salary": 1524305,
  "contractYears": 1,
  "tradeEligible": true
}, {
  "id": "BrooklynNets_11",
  "firstName": "Joe",
  "lastName": "Harris",
  "position": "SG",
  "salary": 1524305,
  "contractYears": 1,
  "tradeEligible": true
}, {
  "id": "BrooklynNets_12",
  "firstName": "Spencer",
  "lastName": "Dinwiddle",
  "position": "PG",
  "salary": 1524305,
  "contractYears": 2,
  "tradeEligible": true
}, {
  "id": "BrooklynNets_14",
  "firstName": "Rondae",
  "lastName": "Hollis-Jefferson",
  "position": "SG",
  "salary": 1471382,
  "contractYears": 2,
  "tradeEligible": true
}, {
  "id": "BrooklynNets_15",
  "firstName": "Isaiah",
  "lastName": "Whitehead",
  "position": "SG",
  "salary": 1312611,
  "contractYears": 3,
  "tradeEligible": true
}];

export const ClevelandCavaliers = [{
  "id": "ClevelandCavaliers_1",
  "firstName": "LeBron",
  "lastName": "James",
  "position": "SF",
  "salary": 33285709,
  "contractYears": 2,
  "tradeEligible": true
}, {
  "id": "ClevelandCavaliers_2",
  "firstName": "Kevin",
  "lastName": "Love",
  "position": "PF",
  "salary": 22642350,
  "contractYears": 3,
  "tradeEligible": true
}, {
  "id": "ClevelandCavaliers_3",
  "firstName": "Kyrie",
  "lastName": "Irving",
  "position": "PG",
  "salary": 18868626,
  "contractYears": 3,
  "tradeEligible": true
}, {
  "id": "ClevelandCavaliers_4",
  "firstName": "Tristan",
  "lastName": "Thompson",
  "position": "C",
  "salary": 16400000,
  "contractYears": 3,
  "tradeEligible": true
}, {
  "id": "ClevelandCavaliers_5",
  "firstName": "JR",
  "lastName": "Smith",
  "position": "SG",
  "salary": 13760000,
  "contractYears": 3,
  "tradeEligible": true
}, {
  "id": "ClevelandCavaliers_6",
  "firstName": "Iman",
  "lastName": "Shumphert",
  "position": "SG",
  "salary": 10337079,
  "contractYears": 2,
  "tradeEligible": true
}, {
  "id": "ClevelandCavaliers_7",
  "firstName": "Channing",
  "lastName": "Frye",
  "position": "C",
  "salary": 7420912,
  "contractYears": 1,
  "tradeEligible": true
}, {
  "id": "ClevelandCavaliers_8",
  "firstName": "Kyle",
  "lastName": "Korver",
  "position": "SG",
  "salary": 7000000,
  "contractYears": 3,
  "tradeEligible": false
}, {
  "id": "ClevelandCavaliers_9",
  "firstName": "Cedi",
  "lastName": "Osman",
  "position": "SF",
  "salary": 2642857,
  "contractYears": 3,
  "tradeEligible": false
}, {
  "id": "ClevelandCavaliers_10",
  "firstName": "Richard",
  "lastName": "Jefferson",
  "position": "SF",
  "salary": 2500000,
  "contractYears": 2,
  "tradeEligible": true
}, {
  "id": "ClevelandCavaliers_11",
  "firstName": "Derrick",
  "lastName": "Rose",
  "position": "PG",
  "salary": 1471382,
  "contractYears": 1,
  "tradeEligible": false
}, {
  "id": "ClevelandCavaliers_12",
  "firstName": "Jeff",
  "lastName": "Green",
  "position": "SF",
  "salary": 1471382,
  "contractYears": 1,
  "tradeEligible": false
}, {
  "id": "ClevelandCavaliers_13",
  "firstName": "Jose",
  "lastName": "Calderon",
  "position": "PG",
  "salary": 1471382,
  "contractYears": 1,
  "tradeEligible": true
}, {
  "id": "ClevelandCavaliers_14",
  "firstName": "Edy",
  "lastName": "Tavares",
  "position": "C",
  "salary": 1312611,
  "contractYears": 2,
  "tradeEligible": true
}, {
  "id": "ClevelandCavaliers_15",
  "firstName": "Kay",
  "lastName": "Felder",
  "position": "PG",
  "salary": 1312611,
  "contractYears": 2,
  "tradeEligible": true
}];

export const NewYorkKnicks = [{
  "id": "NewYorkKnicks_1",
  "firstName": "Carmelo",
  "lastName": "Anthony",
  "position": "SF",
  "salary": 26243760,
  "contractYears": 2,
  "tradeEligible": true
}, {
  "id": "NewYorkKnicks_2",
  "firstName": "Joakim",
  "lastName": "Noah",
  "position": "C",
  "salary": 17765000,
  "contractYears": 3,
  "tradeEligible": true
}, {
  "id": "NewYorkKnicks_3",
  "firstName": "Tim",
  "lastName": "Hardaway Jr.",
  "position": "SG",
  "salary": 16500000,
  "contractYears": 4,
  "tradeEligible": false
}, {
  "id": "NewYorkKnicks_4",
  "firstName": "Courtney",
  "lastName": "Lee",
  "position": "SG",
  "salary": 11747890,
  "contractYears": 3,
  "tradeEligible": true
}, {
  "id": "NewYorkKnicks_5",
  "firstName": "Lance",
  "lastName": "Thomas",
  "position": "SF",
  "salary": 6655325,
  "contractYears": 3,
  "tradeEligible": true
}, {
  "id": "NewYorkKnicks_6",
  "firstName": "Kristpas",
  "lastName": "Porzingis",
  "position": "PF",
  "salary": 4503600,
  "contractYears": 2,
  "tradeEligible": true
}, {
  "id": "NewYorkKnicks_7",
  "firstName": "Kyle",
  "lastName": "O'Quinn",
  "position": "C",
  "salary": 4087500,
  "contractYears": 2,
  "tradeEligible": true
}, {
  "id": "NewYorkKnicks_8",
  "firstName": "Frank",
  "lastName": "Ntilikina",
  "position": "PG",
  "salary": 3501120,
  "contractYears": 4,
  "tradeEligible": true
}, {
  "id": "NewYorkKnicks_9",
  "firstName": "Mindaugas",
  "lastName": "Kuzminskas",
  "position": "PF",
  "salary": 3025035,
  "contractYears": 1,
  "tradeEligible": true
}, {
  "id": "NewYorkKnicks_10",
  "firstName": "Wily",
  "lastName": "Hernangomez",
  "position": "C",
  "salary": 1435750,
  "contractYears": 2,
  "tradeEligible": true
}, {
  "id": "NewYorkKnicks_11",
  "firstName": "Derrick",
  "lastName": "Rose",
  "position": "PG",
  "salary": 1471382,
  "contractYears": 1,
  "tradeEligible": true
}, {
  "id": "NewYorkKnicks_12",
  "firstName": "Chasson",
  "lastName": "Randle",
  "position": "PG",
  "salary": 1312611,
  "contractYears": 2,
  "tradeEligible": true
}];

export const PhoenixSuns = [{
  "id": "PhoenixSuns_1",
  "firstName": "Eric",
  "lastName": "Bledsoe",
  "position": "PG",
  "salary": 14500000,
  "contractYears": 2,
  "tradeEligible": true
}, {
  "id": "PhoenixSuns_2",
  "firstName": "Brandon",
  "lastName": "Knight",
  "position": "PG",
  "salary": 13618750,
  "contractYears": 3,
  "tradeEligible": true
}, {
  "id": "PhoenixSuns_3",
  "firstName": "Tyson",
  "lastName": "Chandler",
  "position": "C",
  "salary": 13000000,
  "contractYears": 2,
  "tradeEligible": true
}, {
  "id": "PhoenixSuns_4",
  "firstName": "Jared",
  "lastName": "Dudley",
  "position": "SF",
  "salary": 10000000,
  "contractYears": 2,
  "tradeEligible": true
}, {
  "id": "PhoenixSuns_5",
  "firstName": "Alan",
  "lastName": "Williams",
  "position": "C",
  "salary": 6000000,
  "contractYears": 3,
  "tradeEligible": false
}, {
  "id": "PhoenixSuns_6",
  "firstName": "Josh",
  "lastName": "Jackson",
  "position": "SF",
  "salary": 5090040,
  "contractYears": 4,
  "tradeEligible": true
}, {
  "id": "PhoenixSuns_7",
  "firstName": "Dragan",
  "lastName": "Bender",
  "position": "PF",
  "salary": 4468800,
  "contractYears": 3,
  "tradeEligible": true
}, {
  "id": "PhoenixSuns_8",
  "firstName": "TJ",
  "lastName": "Warren",
  "position": "SF",
  "salary": 3152931,
  "contractYears": 1,
  "tradeEligible": true
}, {
  "id": "PhoenixSuns_9",
  "firstName": "Marquese",
  "lastName": "Chriss",
  "position": "PF",
  "salary": 3073800,
  "contractYears": 3,
  "tradeEligible": true
}, {
  "id": "PhoenixSuns_10",
  "firstName": "Devin",
  "lastName": "Booker",
  "position": "SG",
  "salary": 2319360,
  "contractYears": 2,
  "tradeEligible": true
}, {
  "id": "PhoenixSuns_11",
  "firstName": "Elijah",
  "lastName": "Millsap",
  "position": "SG",
  "salary": 1524305,
  "contractYears": 1,
  "tradeEligible": true
}, {
  "id": "PhoenixSuns_12",
  "firstName": "Tyler",
  "lastName": "Ulis",
  "position": "PG",
  "salary": 1312611,
  "contractYears": 3,
  "tradeEligible": false
}, {
  "id": "PhoenixSuns_14",
  "firstName": "Derrick",
  "lastName": "Jones Jr.",
  "position": "SF",
  "salary": 1312611,
  "contractYears": 3,
  "tradeEligible": false
}, {
  "id": "PhoenixSuns_15",
  "firstName": "Davon",
  "lastName": "Reed",
  "position": "SG",
  "salary": 815615,
  "contractYears": 4,
  "tradeEligible": false
}];

export const SanAntonioSpurs = [{
  "id": "SanAntonioSpurs_1",
  "firstName": "LaMarcus",
  "lastName": "Aldridge",
  "position": "PF",
  "salary": 21461010,
  "contractYears": 2,
  "tradeEligible": true
}, {
  "id": "SanAntonioSpurs_2",
  "firstName": "Kawhi",
  "lastName": "Leonard",
  "position": "SF",
  "salary": 18868626,
  "contractYears": 3,
  "tradeEligible": true
}, {
  "id": "SanAntonioSpurs_3",
  "firstName": "Pau",
  "lastName": "Gasol",
  "position": "C",
  "salary": 16000000,
  "contractYears": 3,
  "tradeEligible": false
}, {
  "id": "SanAntonioSpurs_4",
  "firstName": "Tony",
  "lastName": "Parker",
  "position": "PG",
  "salary": 15453126,
  "contractYears": 1,
  "tradeEligible": true
}, {
  "id": "SanAntonioSpurs_5",
  "firstName": "Patty",
  "lastName": "Mills",
  "position": "PG",
  "salary": 11235955,
  "contractYears": 4,
  "tradeEligible": false
}, {
  "id": "SanAntonioSpurs_6",
  "firstName": "Danny",
  "lastName": "Green",
  "position": "SG",
  "salary": 10000000,
  "contractYears": 2,
  "tradeEligible": true
}, {
  "id": "SanAntonioSpurs_7",
  "firstName": "Rudy",
  "lastName": "Gay",
  "position": "SF",
  "salary": 8406000,
  "contractYears": 2,
  "tradeEligible": false
}, {
  "id": "SanAntonioSpurs_8",
  "firstName": "Kyle",
  "lastName": "Anderson",
  "position": "SF",
  "salary": 2151704,
  "contractYears": 1,
  "tradeEligible": true
}, {
  "id": "SanAntonioSpurs_9",
  "firstName": "Joffrey",
  "lastName": "Lauvergne",
  "position": "C",
  "salary": 1524305,
  "contractYears": 2,
  "tradeEligible": false
}, {
  "id": "SanAntonioSpurs_10",
  "firstName": "Derrick",
  "lastName": "White",
  "position": "PG",
  "salary": 1404600,
  "contractYears": 4,
  "tradeEligible": true
}, {
  "id": "SanAntonioSpurs_11",
  "firstName": "Dejante",
  "lastName": "Murray",
  "position": "PG",
  "salary": 1312611,
  "contractYears": 3,
  "tradeEligible": true
}, {
  "id": "SanAntonioSpurs_12",
  "firstName": "Bryn",
  "lastName": "Forbes",
  "position": "SG",
  "salary": 1312611,
  "contractYears": 1,
  "tradeEligible": true
}, {
  "id": "SanAntonioSpurs_13",
  "firstName": "Davis",
  "lastName": "Bertans",
  "position": "SF",
  "salary": 1312611,
  "contractYears": 1,
  "tradeEligible": true
}, {
  "id": "SanAntonioSpurs_14",
  "firstName": "Brandon",
  "lastName": "Paul",
  "position": "SG",
  "salary": 815615,
  "contractYears": 2,
  "tradeEligible": false
}];
